local opt = vim.opt

opt.tabstop = 4
opt.shiftwidth = 4
opt.smartindent = true
opt.ignorecase = true
opt.smartcase = true
opt.hlsearch = true
opt.incsearch = true
opt.termguicolors = true
opt.signcolumn = "yes"
opt.scrolloff = 8
opt.wrap = false
opt.updatetime = 50
opt.splitright = true
opt.splitbelow = true
opt.undofile = true
opt.swapfile = false
opt.autoindent = true
opt.autoread = true
opt.breakindent = true
opt.conceallevel = 1
opt.confirm = true
opt.cursorline = true
opt.expandtab = true
opt.number = true
opt.relativenumber = true
